# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct ImportsApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `ImportsApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ ImportsApi }) = "http://your-mattermost-url.com/api/v4"

const _returntypes_list_imports_ImportsApi = Dict{Regex,Type}(
    Regex("^" * replace("400", "x"=>".") * "\$") => AppError,
    Regex("^" * replace("401", "x"=>".") * "\$") => AppError,
    Regex("^" * replace("403", "x"=>".") * "\$") => AppError,
    Regex("^" * replace("404", "x"=>".") * "\$") => AppError,
)

function _oacinternal_list_imports(_api::ImportsApi; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_list_imports_ImportsApi, "/imports", ["bearerAuth", ])
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""List import files

Lists all available import files.  __Minimum server version__: 5.31 ##### Permissions Must have `manage_system` permissions. 

Params:

Return: Nothing, OpenAPI.Clients.ApiResponse
"""
function list_imports(_api::ImportsApi; _mediaType=nothing)
    _ctx = _oacinternal_list_imports(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function list_imports(_api::ImportsApi, response_stream::Channel; _mediaType=nothing)
    _ctx = _oacinternal_list_imports(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export list_imports
