# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ChannelUnreadAt

    ChannelUnreadAt(;
        team_id=nothing,
        channel_id=nothing,
        msg_count=nothing,
        mention_count=nothing,
        last_viewed_at=nothing,
    )

    - team_id::String : The ID of the team the channel belongs to.
    - channel_id::String : The ID of the channel the user has access to..
    - msg_count::Int64 : No. of messages the user has already read.
    - mention_count::Int64 : No. of mentions the user has within the unread posts of the channel.
    - last_viewed_at::Int64 : time in milliseconds when the user last viewed the channel.
"""
Base.@kwdef mutable struct ChannelUnreadAt <: OpenAPI.APIModel
    team_id::Union{Nothing, String} = nothing
    channel_id::Union{Nothing, String} = nothing
    msg_count::Union{Nothing, Int64} = nothing
    mention_count::Union{Nothing, Int64} = nothing
    last_viewed_at::Union{Nothing, Int64} = nothing

    function ChannelUnreadAt(team_id, channel_id, msg_count, mention_count, last_viewed_at, )
        OpenAPI.validate_property(ChannelUnreadAt, Symbol("team_id"), team_id)
        OpenAPI.validate_property(ChannelUnreadAt, Symbol("channel_id"), channel_id)
        OpenAPI.validate_property(ChannelUnreadAt, Symbol("msg_count"), msg_count)
        OpenAPI.validate_property(ChannelUnreadAt, Symbol("mention_count"), mention_count)
        OpenAPI.validate_property(ChannelUnreadAt, Symbol("last_viewed_at"), last_viewed_at)
        return new(team_id, channel_id, msg_count, mention_count, last_viewed_at, )
    end
end # type ChannelUnreadAt

const _property_types_ChannelUnreadAt = Dict{Symbol,String}(Symbol("team_id")=>"String", Symbol("channel_id")=>"String", Symbol("msg_count")=>"Int64", Symbol("mention_count")=>"Int64", Symbol("last_viewed_at")=>"Int64", )
OpenAPI.property_type(::Type{ ChannelUnreadAt }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ChannelUnreadAt[name]))}

function check_required(o::ChannelUnreadAt)
    true
end

function OpenAPI.validate_property(::Type{ ChannelUnreadAt }, name::Symbol, val)
end
