# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""EnvironmentConfig_NativeAppSettings

    EnvironmentConfigNativeAppSettings(;
        AppDownloadLink=nothing,
        AndroidAppDownloadLink=nothing,
        IosAppDownloadLink=nothing,
    )

    - AppDownloadLink::Bool
    - AndroidAppDownloadLink::Bool
    - IosAppDownloadLink::Bool
"""
Base.@kwdef mutable struct EnvironmentConfigNativeAppSettings <: OpenAPI.APIModel
    AppDownloadLink::Union{Nothing, Bool} = nothing
    AndroidAppDownloadLink::Union{Nothing, Bool} = nothing
    IosAppDownloadLink::Union{Nothing, Bool} = nothing

    function EnvironmentConfigNativeAppSettings(AppDownloadLink, AndroidAppDownloadLink, IosAppDownloadLink, )
        OpenAPI.validate_property(EnvironmentConfigNativeAppSettings, Symbol("AppDownloadLink"), AppDownloadLink)
        OpenAPI.validate_property(EnvironmentConfigNativeAppSettings, Symbol("AndroidAppDownloadLink"), AndroidAppDownloadLink)
        OpenAPI.validate_property(EnvironmentConfigNativeAppSettings, Symbol("IosAppDownloadLink"), IosAppDownloadLink)
        return new(AppDownloadLink, AndroidAppDownloadLink, IosAppDownloadLink, )
    end
end # type EnvironmentConfigNativeAppSettings

const _property_types_EnvironmentConfigNativeAppSettings = Dict{Symbol,String}(Symbol("AppDownloadLink")=>"Bool", Symbol("AndroidAppDownloadLink")=>"Bool", Symbol("IosAppDownloadLink")=>"Bool", )
OpenAPI.property_type(::Type{ EnvironmentConfigNativeAppSettings }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_EnvironmentConfigNativeAppSettings[name]))}

function check_required(o::EnvironmentConfigNativeAppSettings)
    true
end

function OpenAPI.validate_property(::Type{ EnvironmentConfigNativeAppSettings }, name::Symbol, val)
end
