# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Config_EmailSettings

    ConfigEmailSettings(;
        EnableSignUpWithEmail=nothing,
        EnableSignInWithEmail=nothing,
        EnableSignInWithUsername=nothing,
        SendEmailNotifications=nothing,
        RequireEmailVerification=nothing,
        FeedbackName=nothing,
        FeedbackEmail=nothing,
        FeedbackOrganization=nothing,
        SMTPUsername=nothing,
        SMTPPassword=nothing,
        SMTPServer=nothing,
        SMTPPort=nothing,
        ConnectionSecurity=nothing,
        InviteSalt=nothing,
        PasswordResetSalt=nothing,
        SendPushNotifications=nothing,
        PushNotificationServer=nothing,
        PushNotificationContents=nothing,
        EnableEmailBatching=nothing,
        EmailBatchingBufferSize=nothing,
        EmailBatchingInterval=nothing,
    )

    - EnableSignUpWithEmail::Bool
    - EnableSignInWithEmail::Bool
    - EnableSignInWithUsername::Bool
    - SendEmailNotifications::Bool
    - RequireEmailVerification::Bool
    - FeedbackName::String
    - FeedbackEmail::String
    - FeedbackOrganization::String
    - SMTPUsername::String
    - SMTPPassword::String
    - SMTPServer::String
    - SMTPPort::String
    - ConnectionSecurity::String
    - InviteSalt::String
    - PasswordResetSalt::String
    - SendPushNotifications::Bool
    - PushNotificationServer::String
    - PushNotificationContents::String
    - EnableEmailBatching::Bool
    - EmailBatchingBufferSize::Int64
    - EmailBatchingInterval::Int64
"""
Base.@kwdef mutable struct ConfigEmailSettings <: OpenAPI.APIModel
    EnableSignUpWithEmail::Union{Nothing, Bool} = nothing
    EnableSignInWithEmail::Union{Nothing, Bool} = nothing
    EnableSignInWithUsername::Union{Nothing, Bool} = nothing
    SendEmailNotifications::Union{Nothing, Bool} = nothing
    RequireEmailVerification::Union{Nothing, Bool} = nothing
    FeedbackName::Union{Nothing, String} = nothing
    FeedbackEmail::Union{Nothing, String} = nothing
    FeedbackOrganization::Union{Nothing, String} = nothing
    SMTPUsername::Union{Nothing, String} = nothing
    SMTPPassword::Union{Nothing, String} = nothing
    SMTPServer::Union{Nothing, String} = nothing
    SMTPPort::Union{Nothing, String} = nothing
    ConnectionSecurity::Union{Nothing, String} = nothing
    InviteSalt::Union{Nothing, String} = nothing
    PasswordResetSalt::Union{Nothing, String} = nothing
    SendPushNotifications::Union{Nothing, Bool} = nothing
    PushNotificationServer::Union{Nothing, String} = nothing
    PushNotificationContents::Union{Nothing, String} = nothing
    EnableEmailBatching::Union{Nothing, Bool} = nothing
    EmailBatchingBufferSize::Union{Nothing, Int64} = nothing
    EmailBatchingInterval::Union{Nothing, Int64} = nothing

    function ConfigEmailSettings(EnableSignUpWithEmail, EnableSignInWithEmail, EnableSignInWithUsername, SendEmailNotifications, RequireEmailVerification, FeedbackName, FeedbackEmail, FeedbackOrganization, SMTPUsername, SMTPPassword, SMTPServer, SMTPPort, ConnectionSecurity, InviteSalt, PasswordResetSalt, SendPushNotifications, PushNotificationServer, PushNotificationContents, EnableEmailBatching, EmailBatchingBufferSize, EmailBatchingInterval, )
        OpenAPI.validate_property(ConfigEmailSettings, Symbol("EnableSignUpWithEmail"), EnableSignUpWithEmail)
        OpenAPI.validate_property(ConfigEmailSettings, Symbol("EnableSignInWithEmail"), EnableSignInWithEmail)
        OpenAPI.validate_property(ConfigEmailSettings, Symbol("EnableSignInWithUsername"), EnableSignInWithUsername)
        OpenAPI.validate_property(ConfigEmailSettings, Symbol("SendEmailNotifications"), SendEmailNotifications)
        OpenAPI.validate_property(ConfigEmailSettings, Symbol("RequireEmailVerification"), RequireEmailVerification)
        OpenAPI.validate_property(ConfigEmailSettings, Symbol("FeedbackName"), FeedbackName)
        OpenAPI.validate_property(ConfigEmailSettings, Symbol("FeedbackEmail"), FeedbackEmail)
        OpenAPI.validate_property(ConfigEmailSettings, Symbol("FeedbackOrganization"), FeedbackOrganization)
        OpenAPI.validate_property(ConfigEmailSettings, Symbol("SMTPUsername"), SMTPUsername)
        OpenAPI.validate_property(ConfigEmailSettings, Symbol("SMTPPassword"), SMTPPassword)
        OpenAPI.validate_property(ConfigEmailSettings, Symbol("SMTPServer"), SMTPServer)
        OpenAPI.validate_property(ConfigEmailSettings, Symbol("SMTPPort"), SMTPPort)
        OpenAPI.validate_property(ConfigEmailSettings, Symbol("ConnectionSecurity"), ConnectionSecurity)
        OpenAPI.validate_property(ConfigEmailSettings, Symbol("InviteSalt"), InviteSalt)
        OpenAPI.validate_property(ConfigEmailSettings, Symbol("PasswordResetSalt"), PasswordResetSalt)
        OpenAPI.validate_property(ConfigEmailSettings, Symbol("SendPushNotifications"), SendPushNotifications)
        OpenAPI.validate_property(ConfigEmailSettings, Symbol("PushNotificationServer"), PushNotificationServer)
        OpenAPI.validate_property(ConfigEmailSettings, Symbol("PushNotificationContents"), PushNotificationContents)
        OpenAPI.validate_property(ConfigEmailSettings, Symbol("EnableEmailBatching"), EnableEmailBatching)
        OpenAPI.validate_property(ConfigEmailSettings, Symbol("EmailBatchingBufferSize"), EmailBatchingBufferSize)
        OpenAPI.validate_property(ConfigEmailSettings, Symbol("EmailBatchingInterval"), EmailBatchingInterval)
        return new(EnableSignUpWithEmail, EnableSignInWithEmail, EnableSignInWithUsername, SendEmailNotifications, RequireEmailVerification, FeedbackName, FeedbackEmail, FeedbackOrganization, SMTPUsername, SMTPPassword, SMTPServer, SMTPPort, ConnectionSecurity, InviteSalt, PasswordResetSalt, SendPushNotifications, PushNotificationServer, PushNotificationContents, EnableEmailBatching, EmailBatchingBufferSize, EmailBatchingInterval, )
    end
end # type ConfigEmailSettings

const _property_types_ConfigEmailSettings = Dict{Symbol,String}(Symbol("EnableSignUpWithEmail")=>"Bool", Symbol("EnableSignInWithEmail")=>"Bool", Symbol("EnableSignInWithUsername")=>"Bool", Symbol("SendEmailNotifications")=>"Bool", Symbol("RequireEmailVerification")=>"Bool", Symbol("FeedbackName")=>"String", Symbol("FeedbackEmail")=>"String", Symbol("FeedbackOrganization")=>"String", Symbol("SMTPUsername")=>"String", Symbol("SMTPPassword")=>"String", Symbol("SMTPServer")=>"String", Symbol("SMTPPort")=>"String", Symbol("ConnectionSecurity")=>"String", Symbol("InviteSalt")=>"String", Symbol("PasswordResetSalt")=>"String", Symbol("SendPushNotifications")=>"Bool", Symbol("PushNotificationServer")=>"String", Symbol("PushNotificationContents")=>"String", Symbol("EnableEmailBatching")=>"Bool", Symbol("EmailBatchingBufferSize")=>"Int64", Symbol("EmailBatchingInterval")=>"Int64", )
OpenAPI.property_type(::Type{ ConfigEmailSettings }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ConfigEmailSettings[name]))}

function check_required(o::ConfigEmailSettings)
    true
end

function OpenAPI.validate_property(::Type{ ConfigEmailSettings }, name::Symbol, val)
end
