# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CheckUserMfa_request

    CheckUserMfaRequest(;
        login_id=nothing,
    )

    - login_id::String : The email or username used to login
"""
Base.@kwdef mutable struct CheckUserMfaRequest <: OpenAPI.APIModel
    login_id::Union{Nothing, String} = nothing

    function CheckUserMfaRequest(login_id, )
        OpenAPI.validate_property(CheckUserMfaRequest, Symbol("login_id"), login_id)
        return new(login_id, )
    end
end # type CheckUserMfaRequest

const _property_types_CheckUserMfaRequest = Dict{Symbol,String}(Symbol("login_id")=>"String", )
OpenAPI.property_type(::Type{ CheckUserMfaRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CheckUserMfaRequest[name]))}

function check_required(o::CheckUserMfaRequest)
    o.login_id === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ CheckUserMfaRequest }, name::Symbol, val)
end
