# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""reoderChecklistItem_request

    ReoderChecklistItemRequest(;
        item_num=nothing,
        new_location=nothing,
    )

    - item_num::Int64 : Zero-based index of the item to reorder.
    - new_location::Int64 : Zero-based index of the new place to move the item to.
"""
Base.@kwdef mutable struct ReoderChecklistItemRequest <: OpenAPI.APIModel
    item_num::Union{Nothing, Int64} = nothing
    new_location::Union{Nothing, Int64} = nothing

    function ReoderChecklistItemRequest(item_num, new_location, )
        OpenAPI.validate_property(ReoderChecklistItemRequest, Symbol("item_num"), item_num)
        OpenAPI.validate_property(ReoderChecklistItemRequest, Symbol("new_location"), new_location)
        return new(item_num, new_location, )
    end
end # type ReoderChecklistItemRequest

const _property_types_ReoderChecklistItemRequest = Dict{Symbol,String}(Symbol("item_num")=>"Int64", Symbol("new_location")=>"Int64", )
OpenAPI.property_type(::Type{ ReoderChecklistItemRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ReoderChecklistItemRequest[name]))}

function check_required(o::ReoderChecklistItemRequest)
    o.item_num === nothing && (return false)
    o.new_location === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ ReoderChecklistItemRequest }, name::Symbol, val)
end
