# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""SetPostReminder_request

    SetPostReminderRequest(;
        target_time=nothing,
    )

    - target_time::Int64 : Target time for the reminder
"""
Base.@kwdef mutable struct SetPostReminderRequest <: OpenAPI.APIModel
    target_time::Union{Nothing, Int64} = nothing

    function SetPostReminderRequest(target_time, )
        OpenAPI.validate_property(SetPostReminderRequest, Symbol("target_time"), target_time)
        return new(target_time, )
    end
end # type SetPostReminderRequest

const _property_types_SetPostReminderRequest = Dict{Symbol,String}(Symbol("target_time")=>"Int64", )
OpenAPI.property_type(::Type{ SetPostReminderRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_SetPostReminderRequest[name]))}

function check_required(o::SetPostReminderRequest)
    o.target_time === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ SetPostReminderRequest }, name::Symbol, val)
end
