# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Config_FileSettings

    ConfigFileSettings(;
        MaxFileSize=nothing,
        DriverName=nothing,
        Directory=nothing,
        EnablePublicLink=nothing,
        PublicLinkSalt=nothing,
        ThumbnailWidth=nothing,
        ThumbnailHeight=nothing,
        PreviewWidth=nothing,
        PreviewHeight=nothing,
        ProfileWidth=nothing,
        ProfileHeight=nothing,
        InitialFont=nothing,
        AmazonS3AccessKeyId=nothing,
        AmazonS3SecretAccessKey=nothing,
        AmazonS3Bucket=nothing,
        AmazonS3Region=nothing,
        AmazonS3Endpoint=nothing,
        AmazonS3SSL=nothing,
    )

    - MaxFileSize::Int64
    - DriverName::String
    - Directory::String
    - EnablePublicLink::Bool
    - PublicLinkSalt::String
    - ThumbnailWidth::Int64
    - ThumbnailHeight::Int64
    - PreviewWidth::Int64
    - PreviewHeight::Int64
    - ProfileWidth::Int64
    - ProfileHeight::Int64
    - InitialFont::String
    - AmazonS3AccessKeyId::String
    - AmazonS3SecretAccessKey::String
    - AmazonS3Bucket::String
    - AmazonS3Region::String
    - AmazonS3Endpoint::String
    - AmazonS3SSL::Bool
"""
Base.@kwdef mutable struct ConfigFileSettings <: OpenAPI.APIModel
    MaxFileSize::Union{Nothing, Int64} = nothing
    DriverName::Union{Nothing, String} = nothing
    Directory::Union{Nothing, String} = nothing
    EnablePublicLink::Union{Nothing, Bool} = nothing
    PublicLinkSalt::Union{Nothing, String} = nothing
    ThumbnailWidth::Union{Nothing, Int64} = nothing
    ThumbnailHeight::Union{Nothing, Int64} = nothing
    PreviewWidth::Union{Nothing, Int64} = nothing
    PreviewHeight::Union{Nothing, Int64} = nothing
    ProfileWidth::Union{Nothing, Int64} = nothing
    ProfileHeight::Union{Nothing, Int64} = nothing
    InitialFont::Union{Nothing, String} = nothing
    AmazonS3AccessKeyId::Union{Nothing, String} = nothing
    AmazonS3SecretAccessKey::Union{Nothing, String} = nothing
    AmazonS3Bucket::Union{Nothing, String} = nothing
    AmazonS3Region::Union{Nothing, String} = nothing
    AmazonS3Endpoint::Union{Nothing, String} = nothing
    AmazonS3SSL::Union{Nothing, Bool} = nothing

    function ConfigFileSettings(MaxFileSize, DriverName, Directory, EnablePublicLink, PublicLinkSalt, ThumbnailWidth, ThumbnailHeight, PreviewWidth, PreviewHeight, ProfileWidth, ProfileHeight, InitialFont, AmazonS3AccessKeyId, AmazonS3SecretAccessKey, AmazonS3Bucket, AmazonS3Region, AmazonS3Endpoint, AmazonS3SSL, )
        OpenAPI.validate_property(ConfigFileSettings, Symbol("MaxFileSize"), MaxFileSize)
        OpenAPI.validate_property(ConfigFileSettings, Symbol("DriverName"), DriverName)
        OpenAPI.validate_property(ConfigFileSettings, Symbol("Directory"), Directory)
        OpenAPI.validate_property(ConfigFileSettings, Symbol("EnablePublicLink"), EnablePublicLink)
        OpenAPI.validate_property(ConfigFileSettings, Symbol("PublicLinkSalt"), PublicLinkSalt)
        OpenAPI.validate_property(ConfigFileSettings, Symbol("ThumbnailWidth"), ThumbnailWidth)
        OpenAPI.validate_property(ConfigFileSettings, Symbol("ThumbnailHeight"), ThumbnailHeight)
        OpenAPI.validate_property(ConfigFileSettings, Symbol("PreviewWidth"), PreviewWidth)
        OpenAPI.validate_property(ConfigFileSettings, Symbol("PreviewHeight"), PreviewHeight)
        OpenAPI.validate_property(ConfigFileSettings, Symbol("ProfileWidth"), ProfileWidth)
        OpenAPI.validate_property(ConfigFileSettings, Symbol("ProfileHeight"), ProfileHeight)
        OpenAPI.validate_property(ConfigFileSettings, Symbol("InitialFont"), InitialFont)
        OpenAPI.validate_property(ConfigFileSettings, Symbol("AmazonS3AccessKeyId"), AmazonS3AccessKeyId)
        OpenAPI.validate_property(ConfigFileSettings, Symbol("AmazonS3SecretAccessKey"), AmazonS3SecretAccessKey)
        OpenAPI.validate_property(ConfigFileSettings, Symbol("AmazonS3Bucket"), AmazonS3Bucket)
        OpenAPI.validate_property(ConfigFileSettings, Symbol("AmazonS3Region"), AmazonS3Region)
        OpenAPI.validate_property(ConfigFileSettings, Symbol("AmazonS3Endpoint"), AmazonS3Endpoint)
        OpenAPI.validate_property(ConfigFileSettings, Symbol("AmazonS3SSL"), AmazonS3SSL)
        return new(MaxFileSize, DriverName, Directory, EnablePublicLink, PublicLinkSalt, ThumbnailWidth, ThumbnailHeight, PreviewWidth, PreviewHeight, ProfileWidth, ProfileHeight, InitialFont, AmazonS3AccessKeyId, AmazonS3SecretAccessKey, AmazonS3Bucket, AmazonS3Region, AmazonS3Endpoint, AmazonS3SSL, )
    end
end # type ConfigFileSettings

const _property_types_ConfigFileSettings = Dict{Symbol,String}(Symbol("MaxFileSize")=>"Int64", Symbol("DriverName")=>"String", Symbol("Directory")=>"String", Symbol("EnablePublicLink")=>"Bool", Symbol("PublicLinkSalt")=>"String", Symbol("ThumbnailWidth")=>"Int64", Symbol("ThumbnailHeight")=>"Int64", Symbol("PreviewWidth")=>"Int64", Symbol("PreviewHeight")=>"Int64", Symbol("ProfileWidth")=>"Int64", Symbol("ProfileHeight")=>"Int64", Symbol("InitialFont")=>"String", Symbol("AmazonS3AccessKeyId")=>"String", Symbol("AmazonS3SecretAccessKey")=>"String", Symbol("AmazonS3Bucket")=>"String", Symbol("AmazonS3Region")=>"String", Symbol("AmazonS3Endpoint")=>"String", Symbol("AmazonS3SSL")=>"Bool", )
OpenAPI.property_type(::Type{ ConfigFileSettings }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ConfigFileSettings[name]))}

function check_required(o::ConfigFileSettings)
    true
end

function OpenAPI.validate_property(::Type{ ConfigFileSettings }, name::Symbol, val)
end
