# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""OpenGraph_audios_inner
Audio object used in OpenGraph metadata of a webpage

    OpenGraphAudiosInner(;
        url=nothing,
        secure_url=nothing,
        type=nothing,
    )

    - url::String
    - secure_url::String
    - type::String
"""
Base.@kwdef mutable struct OpenGraphAudiosInner <: OpenAPI.APIModel
    url::Union{Nothing, String} = nothing
    secure_url::Union{Nothing, String} = nothing
    type::Union{Nothing, String} = nothing

    function OpenGraphAudiosInner(url, secure_url, type, )
        OpenAPI.validate_property(OpenGraphAudiosInner, Symbol("url"), url)
        OpenAPI.validate_property(OpenGraphAudiosInner, Symbol("secure_url"), secure_url)
        OpenAPI.validate_property(OpenGraphAudiosInner, Symbol("type"), type)
        return new(url, secure_url, type, )
    end
end # type OpenGraphAudiosInner

const _property_types_OpenGraphAudiosInner = Dict{Symbol,String}(Symbol("url")=>"String", Symbol("secure_url")=>"String", Symbol("type")=>"String", )
OpenAPI.property_type(::Type{ OpenGraphAudiosInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_OpenGraphAudiosInner[name]))}

function check_required(o::OpenGraphAudiosInner)
    true
end

function OpenAPI.validate_property(::Type{ OpenGraphAudiosInner }, name::Symbol, val)
end
