# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""AttachDeviceId_request

    AttachDeviceIdRequest(;
        device_id=nothing,
    )

    - device_id::String : Mobile device id. For Android prefix the id with &#x60;android:&#x60; and Apple with &#x60;apple:&#x60;
"""
Base.@kwdef mutable struct AttachDeviceIdRequest <: OpenAPI.APIModel
    device_id::Union{Nothing, String} = nothing

    function AttachDeviceIdRequest(device_id, )
        OpenAPI.validate_property(AttachDeviceIdRequest, Symbol("device_id"), device_id)
        return new(device_id, )
    end
end # type AttachDeviceIdRequest

const _property_types_AttachDeviceIdRequest = Dict{Symbol,String}(Symbol("device_id")=>"String", )
OpenAPI.property_type(::Type{ AttachDeviceIdRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_AttachDeviceIdRequest[name]))}

function check_required(o::AttachDeviceIdRequest)
    o.device_id === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ AttachDeviceIdRequest }, name::Symbol, val)
end
