# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""PluginManifest_backend
Deprecated in Mattermost 5.2 release.

    PluginManifestBackend(;
        executable=nothing,
    )

    - executable::String : Path to the executable binary.
"""
Base.@kwdef mutable struct PluginManifestBackend <: OpenAPI.APIModel
    executable::Union{Nothing, String} = nothing

    function PluginManifestBackend(executable, )
        OpenAPI.validate_property(PluginManifestBackend, Symbol("executable"), executable)
        return new(executable, )
    end
end # type PluginManifestBackend

const _property_types_PluginManifestBackend = Dict{Symbol,String}(Symbol("executable")=>"String", )
OpenAPI.property_type(::Type{ PluginManifestBackend }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PluginManifestBackend[name]))}

function check_required(o::PluginManifestBackend)
    true
end

function OpenAPI.validate_property(::Type{ PluginManifestBackend }, name::Symbol, val)
end
