# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""UpdateUserActive_request

    UpdateUserActiveRequest(;
        active=nothing,
    )

    - active::Bool
"""
Base.@kwdef mutable struct UpdateUserActiveRequest <: OpenAPI.APIModel
    active::Union{Nothing, Bool} = nothing

    function UpdateUserActiveRequest(active, )
        OpenAPI.validate_property(UpdateUserActiveRequest, Symbol("active"), active)
        return new(active, )
    end
end # type UpdateUserActiveRequest

const _property_types_UpdateUserActiveRequest = Dict{Symbol,String}(Symbol("active")=>"Bool", )
OpenAPI.property_type(::Type{ UpdateUserActiveRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_UpdateUserActiveRequest[name]))}

function check_required(o::UpdateUserActiveRequest)
    o.active === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ UpdateUserActiveRequest }, name::Symbol, val)
end
