# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CreatePostEphemeral_request

    CreatePostEphemeralRequest(;
        user_id=nothing,
        post=nothing,
    )

    - user_id::String : The target user id for the ephemeral post
    - post::CreatePostEphemeralRequestPost
"""
Base.@kwdef mutable struct CreatePostEphemeralRequest <: OpenAPI.APIModel
    user_id::Union{Nothing, String} = nothing
    post = nothing # spec type: Union{ Nothing, CreatePostEphemeralRequestPost }

    function CreatePostEphemeralRequest(user_id, post, )
        OpenAPI.validate_property(CreatePostEphemeralRequest, Symbol("user_id"), user_id)
        OpenAPI.validate_property(CreatePostEphemeralRequest, Symbol("post"), post)
        return new(user_id, post, )
    end
end # type CreatePostEphemeralRequest

const _property_types_CreatePostEphemeralRequest = Dict{Symbol,String}(Symbol("user_id")=>"String", Symbol("post")=>"CreatePostEphemeralRequestPost", )
OpenAPI.property_type(::Type{ CreatePostEphemeralRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CreatePostEphemeralRequest[name]))}

function check_required(o::CreatePostEphemeralRequest)
    o.user_id === nothing && (return false)
    o.post === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ CreatePostEphemeralRequest }, name::Symbol, val)
end
