# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""PlaybookList

    PlaybookList(;
        total_count=nothing,
        page_count=nothing,
        has_more=nothing,
        items=nothing,
    )

    - total_count::Int64 : The total number of playbooks in the list, regardless of the paging.
    - page_count::Int64 : The total number of pages. This depends on the total number of playbooks in the database and the per_page parameter sent with the request.
    - has_more::Bool : A boolean describing whether there are more pages after the currently returned.
    - items::Vector{Playbook} : The playbooks in this page.
"""
Base.@kwdef mutable struct PlaybookList <: OpenAPI.APIModel
    total_count::Union{Nothing, Int64} = nothing
    page_count::Union{Nothing, Int64} = nothing
    has_more::Union{Nothing, Bool} = nothing
    items::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{Playbook} }

    function PlaybookList(total_count, page_count, has_more, items, )
        OpenAPI.validate_property(PlaybookList, Symbol("total_count"), total_count)
        OpenAPI.validate_property(PlaybookList, Symbol("page_count"), page_count)
        OpenAPI.validate_property(PlaybookList, Symbol("has_more"), has_more)
        OpenAPI.validate_property(PlaybookList, Symbol("items"), items)
        return new(total_count, page_count, has_more, items, )
    end
end # type PlaybookList

const _property_types_PlaybookList = Dict{Symbol,String}(Symbol("total_count")=>"Int64", Symbol("page_count")=>"Int64", Symbol("has_more")=>"Bool", Symbol("items")=>"Vector{Playbook}", )
OpenAPI.property_type(::Type{ PlaybookList }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_PlaybookList[name]))}

function check_required(o::PlaybookList)
    true
end

function OpenAPI.validate_property(::Type{ PlaybookList }, name::Symbol, val)
    if name === Symbol("total_count")
        OpenAPI.validate_param(name, "PlaybookList", :format, val, "int32")
    end
    if name === Symbol("page_count")
        OpenAPI.validate_param(name, "PlaybookList", :format, val, "int32")
    end
end
