# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""SearchTeamsForRetentionPolicy_request

    SearchTeamsForRetentionPolicyRequest(;
        term=nothing,
    )

    - term::String : The search term to match against the name or display name of teams
"""
Base.@kwdef mutable struct SearchTeamsForRetentionPolicyRequest <: OpenAPI.APIModel
    term::Union{Nothing, String} = nothing

    function SearchTeamsForRetentionPolicyRequest(term, )
        OpenAPI.validate_property(SearchTeamsForRetentionPolicyRequest, Symbol("term"), term)
        return new(term, )
    end
end # type SearchTeamsForRetentionPolicyRequest

const _property_types_SearchTeamsForRetentionPolicyRequest = Dict{Symbol,String}(Symbol("term")=>"String", )
OpenAPI.property_type(::Type{ SearchTeamsForRetentionPolicyRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_SearchTeamsForRetentionPolicyRequest[name]))}

function check_required(o::SearchTeamsForRetentionPolicyRequest)
    true
end

function OpenAPI.validate_property(::Type{ SearchTeamsForRetentionPolicyRequest }, name::Symbol, val)
end
