# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""GroupWithSchemeAdmin
group augmented with scheme admin information

    GroupWithSchemeAdmin(;
        group=nothing,
        scheme_admin=nothing,
    )

    - group::Group
    - scheme_admin::Bool
"""
Base.@kwdef mutable struct GroupWithSchemeAdmin <: OpenAPI.APIModel
    group = nothing # spec type: Union{ Nothing, Group }
    scheme_admin::Union{Nothing, Bool} = nothing

    function GroupWithSchemeAdmin(group, scheme_admin, )
        OpenAPI.validate_property(GroupWithSchemeAdmin, Symbol("group"), group)
        OpenAPI.validate_property(GroupWithSchemeAdmin, Symbol("scheme_admin"), scheme_admin)
        return new(group, scheme_admin, )
    end
end # type GroupWithSchemeAdmin

const _property_types_GroupWithSchemeAdmin = Dict{Symbol,String}(Symbol("group")=>"Group", Symbol("scheme_admin")=>"Bool", )
OpenAPI.property_type(::Type{ GroupWithSchemeAdmin }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_GroupWithSchemeAdmin[name]))}

function check_required(o::GroupWithSchemeAdmin)
    true
end

function OpenAPI.validate_property(::Type{ GroupWithSchemeAdmin }, name::Symbol, val)
end
