# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""EnvironmentConfig_ServiceSettings

    EnvironmentConfigServiceSettings(;
        SiteURL=nothing,
        ListenAddress=nothing,
        ConnectionSecurity=nothing,
        TLSCertFile=nothing,
        TLSKeyFile=nothing,
        UseLetsEncrypt=nothing,
        LetsEncryptCertificateCacheFile=nothing,
        Forward80To443=nothing,
        ReadTimeout=nothing,
        WriteTimeout=nothing,
        MaximumLoginAttempts=nothing,
        SegmentDeveloperKey=nothing,
        GoogleDeveloperKey=nothing,
        EnableOAuthServiceProvider=nothing,
        EnableIncomingWebhooks=nothing,
        EnableOutgoingWebhooks=nothing,
        EnableCommands=nothing,
        EnableOnlyAdminIntegrations=nothing,
        EnablePostUsernameOverride=nothing,
        EnablePostIconOverride=nothing,
        EnableTesting=nothing,
        EnableDeveloper=nothing,
        EnableSecurityFixAlert=nothing,
        EnableInsecureOutgoingConnections=nothing,
        EnableMultifactorAuthentication=nothing,
        EnforceMultifactorAuthentication=nothing,
        AllowCorsFrom=nothing,
        SessionLengthWebInDays=nothing,
        SessionLengthMobileInDays=nothing,
        SessionLengthSSOInDays=nothing,
        SessionCacheInMinutes=nothing,
        WebsocketSecurePort=nothing,
        WebsocketPort=nothing,
        WebserverMode=nothing,
        EnableCustomEmoji=nothing,
        RestrictCustomEmojiCreation=nothing,
    )

    - SiteURL::Bool
    - ListenAddress::Bool
    - ConnectionSecurity::Bool
    - TLSCertFile::Bool
    - TLSKeyFile::Bool
    - UseLetsEncrypt::Bool
    - LetsEncryptCertificateCacheFile::Bool
    - Forward80To443::Bool
    - ReadTimeout::Bool
    - WriteTimeout::Bool
    - MaximumLoginAttempts::Bool
    - SegmentDeveloperKey::Bool
    - GoogleDeveloperKey::Bool
    - EnableOAuthServiceProvider::Bool
    - EnableIncomingWebhooks::Bool
    - EnableOutgoingWebhooks::Bool
    - EnableCommands::Bool
    - EnableOnlyAdminIntegrations::Bool
    - EnablePostUsernameOverride::Bool
    - EnablePostIconOverride::Bool
    - EnableTesting::Bool
    - EnableDeveloper::Bool
    - EnableSecurityFixAlert::Bool
    - EnableInsecureOutgoingConnections::Bool
    - EnableMultifactorAuthentication::Bool
    - EnforceMultifactorAuthentication::Bool
    - AllowCorsFrom::Bool
    - SessionLengthWebInDays::Bool
    - SessionLengthMobileInDays::Bool
    - SessionLengthSSOInDays::Bool
    - SessionCacheInMinutes::Bool
    - WebsocketSecurePort::Bool
    - WebsocketPort::Bool
    - WebserverMode::Bool
    - EnableCustomEmoji::Bool
    - RestrictCustomEmojiCreation::Bool
"""
Base.@kwdef mutable struct EnvironmentConfigServiceSettings <: OpenAPI.APIModel
    SiteURL::Union{Nothing, Bool} = nothing
    ListenAddress::Union{Nothing, Bool} = nothing
    ConnectionSecurity::Union{Nothing, Bool} = nothing
    TLSCertFile::Union{Nothing, Bool} = nothing
    TLSKeyFile::Union{Nothing, Bool} = nothing
    UseLetsEncrypt::Union{Nothing, Bool} = nothing
    LetsEncryptCertificateCacheFile::Union{Nothing, Bool} = nothing
    Forward80To443::Union{Nothing, Bool} = nothing
    ReadTimeout::Union{Nothing, Bool} = nothing
    WriteTimeout::Union{Nothing, Bool} = nothing
    MaximumLoginAttempts::Union{Nothing, Bool} = nothing
    SegmentDeveloperKey::Union{Nothing, Bool} = nothing
    GoogleDeveloperKey::Union{Nothing, Bool} = nothing
    EnableOAuthServiceProvider::Union{Nothing, Bool} = nothing
    EnableIncomingWebhooks::Union{Nothing, Bool} = nothing
    EnableOutgoingWebhooks::Union{Nothing, Bool} = nothing
    EnableCommands::Union{Nothing, Bool} = nothing
    EnableOnlyAdminIntegrations::Union{Nothing, Bool} = nothing
    EnablePostUsernameOverride::Union{Nothing, Bool} = nothing
    EnablePostIconOverride::Union{Nothing, Bool} = nothing
    EnableTesting::Union{Nothing, Bool} = nothing
    EnableDeveloper::Union{Nothing, Bool} = nothing
    EnableSecurityFixAlert::Union{Nothing, Bool} = nothing
    EnableInsecureOutgoingConnections::Union{Nothing, Bool} = nothing
    EnableMultifactorAuthentication::Union{Nothing, Bool} = nothing
    EnforceMultifactorAuthentication::Union{Nothing, Bool} = nothing
    AllowCorsFrom::Union{Nothing, Bool} = nothing
    SessionLengthWebInDays::Union{Nothing, Bool} = nothing
    SessionLengthMobileInDays::Union{Nothing, Bool} = nothing
    SessionLengthSSOInDays::Union{Nothing, Bool} = nothing
    SessionCacheInMinutes::Union{Nothing, Bool} = nothing
    WebsocketSecurePort::Union{Nothing, Bool} = nothing
    WebsocketPort::Union{Nothing, Bool} = nothing
    WebserverMode::Union{Nothing, Bool} = nothing
    EnableCustomEmoji::Union{Nothing, Bool} = nothing
    RestrictCustomEmojiCreation::Union{Nothing, Bool} = nothing

    function EnvironmentConfigServiceSettings(SiteURL, ListenAddress, ConnectionSecurity, TLSCertFile, TLSKeyFile, UseLetsEncrypt, LetsEncryptCertificateCacheFile, Forward80To443, ReadTimeout, WriteTimeout, MaximumLoginAttempts, SegmentDeveloperKey, GoogleDeveloperKey, EnableOAuthServiceProvider, EnableIncomingWebhooks, EnableOutgoingWebhooks, EnableCommands, EnableOnlyAdminIntegrations, EnablePostUsernameOverride, EnablePostIconOverride, EnableTesting, EnableDeveloper, EnableSecurityFixAlert, EnableInsecureOutgoingConnections, EnableMultifactorAuthentication, EnforceMultifactorAuthentication, AllowCorsFrom, SessionLengthWebInDays, SessionLengthMobileInDays, SessionLengthSSOInDays, SessionCacheInMinutes, WebsocketSecurePort, WebsocketPort, WebserverMode, EnableCustomEmoji, RestrictCustomEmojiCreation, )
        OpenAPI.validate_property(EnvironmentConfigServiceSettings, Symbol("SiteURL"), SiteURL)
        OpenAPI.validate_property(EnvironmentConfigServiceSettings, Symbol("ListenAddress"), ListenAddress)
        OpenAPI.validate_property(EnvironmentConfigServiceSettings, Symbol("ConnectionSecurity"), ConnectionSecurity)
        OpenAPI.validate_property(EnvironmentConfigServiceSettings, Symbol("TLSCertFile"), TLSCertFile)
        OpenAPI.validate_property(EnvironmentConfigServiceSettings, Symbol("TLSKeyFile"), TLSKeyFile)
        OpenAPI.validate_property(EnvironmentConfigServiceSettings, Symbol("UseLetsEncrypt"), UseLetsEncrypt)
        OpenAPI.validate_property(EnvironmentConfigServiceSettings, Symbol("LetsEncryptCertificateCacheFile"), LetsEncryptCertificateCacheFile)
        OpenAPI.validate_property(EnvironmentConfigServiceSettings, Symbol("Forward80To443"), Forward80To443)
        OpenAPI.validate_property(EnvironmentConfigServiceSettings, Symbol("ReadTimeout"), ReadTimeout)
        OpenAPI.validate_property(EnvironmentConfigServiceSettings, Symbol("WriteTimeout"), WriteTimeout)
        OpenAPI.validate_property(EnvironmentConfigServiceSettings, Symbol("MaximumLoginAttempts"), MaximumLoginAttempts)
        OpenAPI.validate_property(EnvironmentConfigServiceSettings, Symbol("SegmentDeveloperKey"), SegmentDeveloperKey)
        OpenAPI.validate_property(EnvironmentConfigServiceSettings, Symbol("GoogleDeveloperKey"), GoogleDeveloperKey)
        OpenAPI.validate_property(EnvironmentConfigServiceSettings, Symbol("EnableOAuthServiceProvider"), EnableOAuthServiceProvider)
        OpenAPI.validate_property(EnvironmentConfigServiceSettings, Symbol("EnableIncomingWebhooks"), EnableIncomingWebhooks)
        OpenAPI.validate_property(EnvironmentConfigServiceSettings, Symbol("EnableOutgoingWebhooks"), EnableOutgoingWebhooks)
        OpenAPI.validate_property(EnvironmentConfigServiceSettings, Symbol("EnableCommands"), EnableCommands)
        OpenAPI.validate_property(EnvironmentConfigServiceSettings, Symbol("EnableOnlyAdminIntegrations"), EnableOnlyAdminIntegrations)
        OpenAPI.validate_property(EnvironmentConfigServiceSettings, Symbol("EnablePostUsernameOverride"), EnablePostUsernameOverride)
        OpenAPI.validate_property(EnvironmentConfigServiceSettings, Symbol("EnablePostIconOverride"), EnablePostIconOverride)
        OpenAPI.validate_property(EnvironmentConfigServiceSettings, Symbol("EnableTesting"), EnableTesting)
        OpenAPI.validate_property(EnvironmentConfigServiceSettings, Symbol("EnableDeveloper"), EnableDeveloper)
        OpenAPI.validate_property(EnvironmentConfigServiceSettings, Symbol("EnableSecurityFixAlert"), EnableSecurityFixAlert)
        OpenAPI.validate_property(EnvironmentConfigServiceSettings, Symbol("EnableInsecureOutgoingConnections"), EnableInsecureOutgoingConnections)
        OpenAPI.validate_property(EnvironmentConfigServiceSettings, Symbol("EnableMultifactorAuthentication"), EnableMultifactorAuthentication)
        OpenAPI.validate_property(EnvironmentConfigServiceSettings, Symbol("EnforceMultifactorAuthentication"), EnforceMultifactorAuthentication)
        OpenAPI.validate_property(EnvironmentConfigServiceSettings, Symbol("AllowCorsFrom"), AllowCorsFrom)
        OpenAPI.validate_property(EnvironmentConfigServiceSettings, Symbol("SessionLengthWebInDays"), SessionLengthWebInDays)
        OpenAPI.validate_property(EnvironmentConfigServiceSettings, Symbol("SessionLengthMobileInDays"), SessionLengthMobileInDays)
        OpenAPI.validate_property(EnvironmentConfigServiceSettings, Symbol("SessionLengthSSOInDays"), SessionLengthSSOInDays)
        OpenAPI.validate_property(EnvironmentConfigServiceSettings, Symbol("SessionCacheInMinutes"), SessionCacheInMinutes)
        OpenAPI.validate_property(EnvironmentConfigServiceSettings, Symbol("WebsocketSecurePort"), WebsocketSecurePort)
        OpenAPI.validate_property(EnvironmentConfigServiceSettings, Symbol("WebsocketPort"), WebsocketPort)
        OpenAPI.validate_property(EnvironmentConfigServiceSettings, Symbol("WebserverMode"), WebserverMode)
        OpenAPI.validate_property(EnvironmentConfigServiceSettings, Symbol("EnableCustomEmoji"), EnableCustomEmoji)
        OpenAPI.validate_property(EnvironmentConfigServiceSettings, Symbol("RestrictCustomEmojiCreation"), RestrictCustomEmojiCreation)
        return new(SiteURL, ListenAddress, ConnectionSecurity, TLSCertFile, TLSKeyFile, UseLetsEncrypt, LetsEncryptCertificateCacheFile, Forward80To443, ReadTimeout, WriteTimeout, MaximumLoginAttempts, SegmentDeveloperKey, GoogleDeveloperKey, EnableOAuthServiceProvider, EnableIncomingWebhooks, EnableOutgoingWebhooks, EnableCommands, EnableOnlyAdminIntegrations, EnablePostUsernameOverride, EnablePostIconOverride, EnableTesting, EnableDeveloper, EnableSecurityFixAlert, EnableInsecureOutgoingConnections, EnableMultifactorAuthentication, EnforceMultifactorAuthentication, AllowCorsFrom, SessionLengthWebInDays, SessionLengthMobileInDays, SessionLengthSSOInDays, SessionCacheInMinutes, WebsocketSecurePort, WebsocketPort, WebserverMode, EnableCustomEmoji, RestrictCustomEmojiCreation, )
    end
end # type EnvironmentConfigServiceSettings

const _property_types_EnvironmentConfigServiceSettings = Dict{Symbol,String}(Symbol("SiteURL")=>"Bool", Symbol("ListenAddress")=>"Bool", Symbol("ConnectionSecurity")=>"Bool", Symbol("TLSCertFile")=>"Bool", Symbol("TLSKeyFile")=>"Bool", Symbol("UseLetsEncrypt")=>"Bool", Symbol("LetsEncryptCertificateCacheFile")=>"Bool", Symbol("Forward80To443")=>"Bool", Symbol("ReadTimeout")=>"Bool", Symbol("WriteTimeout")=>"Bool", Symbol("MaximumLoginAttempts")=>"Bool", Symbol("SegmentDeveloperKey")=>"Bool", Symbol("GoogleDeveloperKey")=>"Bool", Symbol("EnableOAuthServiceProvider")=>"Bool", Symbol("EnableIncomingWebhooks")=>"Bool", Symbol("EnableOutgoingWebhooks")=>"Bool", Symbol("EnableCommands")=>"Bool", Symbol("EnableOnlyAdminIntegrations")=>"Bool", Symbol("EnablePostUsernameOverride")=>"Bool", Symbol("EnablePostIconOverride")=>"Bool", Symbol("EnableTesting")=>"Bool", Symbol("EnableDeveloper")=>"Bool", Symbol("EnableSecurityFixAlert")=>"Bool", Symbol("EnableInsecureOutgoingConnections")=>"Bool", Symbol("EnableMultifactorAuthentication")=>"Bool", Symbol("EnforceMultifactorAuthentication")=>"Bool", Symbol("AllowCorsFrom")=>"Bool", Symbol("SessionLengthWebInDays")=>"Bool", Symbol("SessionLengthMobileInDays")=>"Bool", Symbol("SessionLengthSSOInDays")=>"Bool", Symbol("SessionCacheInMinutes")=>"Bool", Symbol("WebsocketSecurePort")=>"Bool", Symbol("WebsocketPort")=>"Bool", Symbol("WebserverMode")=>"Bool", Symbol("EnableCustomEmoji")=>"Bool", Symbol("RestrictCustomEmojiCreation")=>"Bool", )
OpenAPI.property_type(::Type{ EnvironmentConfigServiceSettings }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_EnvironmentConfigServiceSettings[name]))}

function check_required(o::EnvironmentConfigServiceSettings)
    true
end

function OpenAPI.validate_property(::Type{ EnvironmentConfigServiceSettings }, name::Symbol, val)
end
