# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Config_MetricsSettings

    ConfigMetricsSettings(;
        Enable=nothing,
        BlockProfileRate=nothing,
        ListenAddress=nothing,
    )

    - Enable::Bool
    - BlockProfileRate::Int64
    - ListenAddress::String
"""
Base.@kwdef mutable struct ConfigMetricsSettings <: OpenAPI.APIModel
    Enable::Union{Nothing, Bool} = nothing
    BlockProfileRate::Union{Nothing, Int64} = nothing
    ListenAddress::Union{Nothing, String} = nothing

    function ConfigMetricsSettings(Enable, BlockProfileRate, ListenAddress, )
        OpenAPI.validate_property(ConfigMetricsSettings, Symbol("Enable"), Enable)
        OpenAPI.validate_property(ConfigMetricsSettings, Symbol("BlockProfileRate"), BlockProfileRate)
        OpenAPI.validate_property(ConfigMetricsSettings, Symbol("ListenAddress"), ListenAddress)
        return new(Enable, BlockProfileRate, ListenAddress, )
    end
end # type ConfigMetricsSettings

const _property_types_ConfigMetricsSettings = Dict{Symbol,String}(Symbol("Enable")=>"Bool", Symbol("BlockProfileRate")=>"Int64", Symbol("ListenAddress")=>"String", )
OpenAPI.property_type(::Type{ ConfigMetricsSettings }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ConfigMetricsSettings[name]))}

function check_required(o::ConfigMetricsSettings)
    true
end

function OpenAPI.validate_property(::Type{ ConfigMetricsSettings }, name::Symbol, val)
end
