# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""GetRedirectLocation_200_response

    GetRedirectLocation200Response(;
        location=nothing,
    )

    - location::String
"""
Base.@kwdef mutable struct GetRedirectLocation200Response <: OpenAPI.APIModel
    location::Union{Nothing, String} = nothing

    function GetRedirectLocation200Response(location, )
        OpenAPI.validate_property(GetRedirectLocation200Response, Symbol("location"), location)
        return new(location, )
    end
end # type GetRedirectLocation200Response

const _property_types_GetRedirectLocation200Response = Dict{Symbol,String}(Symbol("location")=>"String", )
OpenAPI.property_type(::Type{ GetRedirectLocation200Response }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_GetRedirectLocation200Response[name]))}

function check_required(o::GetRedirectLocation200Response)
    true
end

function OpenAPI.validate_property(::Type{ GetRedirectLocation200Response }, name::Symbol, val)
end
