# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""RegenCommandToken_200_response

    RegenCommandToken200Response(;
        token=nothing,
    )

    - token::String : The new token
"""
Base.@kwdef mutable struct RegenCommandToken200Response <: OpenAPI.APIModel
    token::Union{Nothing, String} = nothing

    function RegenCommandToken200Response(token, )
        OpenAPI.validate_property(RegenCommandToken200Response, Symbol("token"), token)
        return new(token, )
    end
end # type RegenCommandToken200Response

const _property_types_RegenCommandToken200Response = Dict{Symbol,String}(Symbol("token")=>"String", )
OpenAPI.property_type(::Type{ RegenCommandToken200Response }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_RegenCommandToken200Response[name]))}

function check_required(o::RegenCommandToken200Response)
    true
end

function OpenAPI.validate_property(::Type{ RegenCommandToken200Response }, name::Symbol, val)
end
