# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""createPlaybookRunFromDialog_request_submission
Map of the dialog fields to their values

    CreatePlaybookRunFromDialogRequestSubmission(;
        playbookID=nothing,
        playbookRunName=nothing,
        playbookRunDescription=nothing,
    )

    - playbookID::String : ID of the playbook to create the playbook run from.
    - playbookRunName::String : The name of the playbook run to be created.
    - playbookRunDescription::String : An optional description of the playbook run.
"""
Base.@kwdef mutable struct CreatePlaybookRunFromDialogRequestSubmission <: OpenAPI.APIModel
    playbookID::Union{Nothing, String} = nothing
    playbookRunName::Union{Nothing, String} = nothing
    playbookRunDescription::Union{Nothing, String} = nothing

    function CreatePlaybookRunFromDialogRequestSubmission(playbookID, playbookRunName, playbookRunDescription, )
        OpenAPI.validate_property(CreatePlaybookRunFromDialogRequestSubmission, Symbol("playbookID"), playbookID)
        OpenAPI.validate_property(CreatePlaybookRunFromDialogRequestSubmission, Symbol("playbookRunName"), playbookRunName)
        OpenAPI.validate_property(CreatePlaybookRunFromDialogRequestSubmission, Symbol("playbookRunDescription"), playbookRunDescription)
        return new(playbookID, playbookRunName, playbookRunDescription, )
    end
end # type CreatePlaybookRunFromDialogRequestSubmission

const _property_types_CreatePlaybookRunFromDialogRequestSubmission = Dict{Symbol,String}(Symbol("playbookID")=>"String", Symbol("playbookRunName")=>"String", Symbol("playbookRunDescription")=>"String", )
OpenAPI.property_type(::Type{ CreatePlaybookRunFromDialogRequestSubmission }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CreatePlaybookRunFromDialogRequestSubmission[name]))}

function check_required(o::CreatePlaybookRunFromDialogRequestSubmission)
    o.playbookID === nothing && (return false)
    o.playbookRunName === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ CreatePlaybookRunFromDialogRequestSubmission }, name::Symbol, val)
end
