# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""UpdatePost_request

    UpdatePostRequest(;
        id=nothing,
        is_pinned=nothing,
        message=nothing,
        has_reactions=nothing,
        props=nothing,
    )

    - id::String : ID of the post to update
    - is_pinned::Bool : Set to &#x60;true&#x60; to pin the post to the channel it is in
    - message::String : The message text of the post
    - has_reactions::Bool : Set to &#x60;true&#x60; if the post has reactions to it
    - props::String : A general JSON property bag to attach to the post
"""
Base.@kwdef mutable struct UpdatePostRequest <: OpenAPI.APIModel
    id::Union{Nothing, String} = nothing
    is_pinned::Union{Nothing, Bool} = nothing
    message::Union{Nothing, String} = nothing
    has_reactions::Union{Nothing, Bool} = nothing
    props::Union{Nothing, String} = nothing

    function UpdatePostRequest(id, is_pinned, message, has_reactions, props, )
        OpenAPI.validate_property(UpdatePostRequest, Symbol("id"), id)
        OpenAPI.validate_property(UpdatePostRequest, Symbol("is_pinned"), is_pinned)
        OpenAPI.validate_property(UpdatePostRequest, Symbol("message"), message)
        OpenAPI.validate_property(UpdatePostRequest, Symbol("has_reactions"), has_reactions)
        OpenAPI.validate_property(UpdatePostRequest, Symbol("props"), props)
        return new(id, is_pinned, message, has_reactions, props, )
    end
end # type UpdatePostRequest

const _property_types_UpdatePostRequest = Dict{Symbol,String}(Symbol("id")=>"String", Symbol("is_pinned")=>"Bool", Symbol("message")=>"String", Symbol("has_reactions")=>"Bool", Symbol("props")=>"String", )
OpenAPI.property_type(::Type{ UpdatePostRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_UpdatePostRequest[name]))}

function check_required(o::UpdatePostRequest)
    o.id === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ UpdatePostRequest }, name::Symbol, val)
end
