# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""UpdateTeam_request

    UpdateTeamRequest(;
        id=nothing,
        display_name=nothing,
        description=nothing,
        company_name=nothing,
        allowed_domains=nothing,
        invite_id=nothing,
        allow_open_invite=nothing,
    )

    - id::String
    - display_name::String
    - description::String
    - company_name::String
    - allowed_domains::String
    - invite_id::String
    - allow_open_invite::String
"""
Base.@kwdef mutable struct UpdateTeamRequest <: OpenAPI.APIModel
    id::Union{Nothing, String} = nothing
    display_name::Union{Nothing, String} = nothing
    description::Union{Nothing, String} = nothing
    company_name::Union{Nothing, String} = nothing
    allowed_domains::Union{Nothing, String} = nothing
    invite_id::Union{Nothing, String} = nothing
    allow_open_invite::Union{Nothing, String} = nothing

    function UpdateTeamRequest(id, display_name, description, company_name, allowed_domains, invite_id, allow_open_invite, )
        OpenAPI.validate_property(UpdateTeamRequest, Symbol("id"), id)
        OpenAPI.validate_property(UpdateTeamRequest, Symbol("display_name"), display_name)
        OpenAPI.validate_property(UpdateTeamRequest, Symbol("description"), description)
        OpenAPI.validate_property(UpdateTeamRequest, Symbol("company_name"), company_name)
        OpenAPI.validate_property(UpdateTeamRequest, Symbol("allowed_domains"), allowed_domains)
        OpenAPI.validate_property(UpdateTeamRequest, Symbol("invite_id"), invite_id)
        OpenAPI.validate_property(UpdateTeamRequest, Symbol("allow_open_invite"), allow_open_invite)
        return new(id, display_name, description, company_name, allowed_domains, invite_id, allow_open_invite, )
    end
end # type UpdateTeamRequest

const _property_types_UpdateTeamRequest = Dict{Symbol,String}(Symbol("id")=>"String", Symbol("display_name")=>"String", Symbol("description")=>"String", Symbol("company_name")=>"String", Symbol("allowed_domains")=>"String", Symbol("invite_id")=>"String", Symbol("allow_open_invite")=>"String", )
OpenAPI.property_type(::Type{ UpdateTeamRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_UpdateTeamRequest[name]))}

function check_required(o::UpdateTeamRequest)
    o.id === nothing && (return false)
    o.display_name === nothing && (return false)
    o.description === nothing && (return false)
    o.company_name === nothing && (return false)
    o.allowed_domains === nothing && (return false)
    o.invite_id === nothing && (return false)
    o.allow_open_invite === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ UpdateTeamRequest }, name::Symbol, val)
end
