# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""UpdateCloudCustomer_request

    UpdateCloudCustomerRequest(;
        name=nothing,
        email=nothing,
        contact_first_name=nothing,
        contact_last_name=nothing,
        num_employees=nothing,
    )

    - name::String
    - email::String
    - contact_first_name::String
    - contact_last_name::String
    - num_employees::String
"""
Base.@kwdef mutable struct UpdateCloudCustomerRequest <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing
    email::Union{Nothing, String} = nothing
    contact_first_name::Union{Nothing, String} = nothing
    contact_last_name::Union{Nothing, String} = nothing
    num_employees::Union{Nothing, String} = nothing

    function UpdateCloudCustomerRequest(name, email, contact_first_name, contact_last_name, num_employees, )
        OpenAPI.validate_property(UpdateCloudCustomerRequest, Symbol("name"), name)
        OpenAPI.validate_property(UpdateCloudCustomerRequest, Symbol("email"), email)
        OpenAPI.validate_property(UpdateCloudCustomerRequest, Symbol("contact_first_name"), contact_first_name)
        OpenAPI.validate_property(UpdateCloudCustomerRequest, Symbol("contact_last_name"), contact_last_name)
        OpenAPI.validate_property(UpdateCloudCustomerRequest, Symbol("num_employees"), num_employees)
        return new(name, email, contact_first_name, contact_last_name, num_employees, )
    end
end # type UpdateCloudCustomerRequest

const _property_types_UpdateCloudCustomerRequest = Dict{Symbol,String}(Symbol("name")=>"String", Symbol("email")=>"String", Symbol("contact_first_name")=>"String", Symbol("contact_last_name")=>"String", Symbol("num_employees")=>"String", )
OpenAPI.property_type(::Type{ UpdateCloudCustomerRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_UpdateCloudCustomerRequest[name]))}

function check_required(o::UpdateCloudCustomerRequest)
    true
end

function OpenAPI.validate_property(::Type{ UpdateCloudCustomerRequest }, name::Symbol, val)
end
