# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""GetFileLink_200_response

    GetFileLink200Response(;
        link=nothing,
    )

    - link::String
"""
Base.@kwdef mutable struct GetFileLink200Response <: OpenAPI.APIModel
    link::Union{Nothing, String} = nothing

    function GetFileLink200Response(link, )
        OpenAPI.validate_property(GetFileLink200Response, Symbol("link"), link)
        return new(link, )
    end
end # type GetFileLink200Response

const _property_types_GetFileLink200Response = Dict{Symbol,String}(Symbol("link")=>"String", )
OpenAPI.property_type(::Type{ GetFileLink200Response }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_GetFileLink200Response[name]))}

function check_required(o::GetFileLink200Response)
    true
end

function OpenAPI.validate_property(::Type{ GetFileLink200Response }, name::Symbol, val)
end
