# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""IntegrityCheckResult
an object with the result of the integrity check.

    IntegrityCheckResult(;
        data=nothing,
        err=nothing,
    )

    - data::RelationalIntegrityCheckData
    - err::String : a string value set in case of error.
"""
Base.@kwdef mutable struct IntegrityCheckResult <: OpenAPI.APIModel
    data = nothing # spec type: Union{ Nothing, RelationalIntegrityCheckData }
    err::Union{Nothing, String} = nothing

    function IntegrityCheckResult(data, err, )
        OpenAPI.validate_property(IntegrityCheckResult, Symbol("data"), data)
        OpenAPI.validate_property(IntegrityCheckResult, Symbol("err"), err)
        return new(data, err, )
    end
end # type IntegrityCheckResult

const _property_types_IntegrityCheckResult = Dict{Symbol,String}(Symbol("data")=>"RelationalIntegrityCheckData", Symbol("err")=>"String", )
OpenAPI.property_type(::Type{ IntegrityCheckResult }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_IntegrityCheckResult[name]))}

function check_required(o::IntegrityCheckResult)
    true
end

function OpenAPI.validate_property(::Type{ IntegrityCheckResult }, name::Symbol, val)
end
