# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""TeamsLimits

    TeamsLimits(;
        active=nothing,
    )

    - active::Int64
"""
Base.@kwdef mutable struct TeamsLimits <: OpenAPI.APIModel
    active::Union{Nothing, Int64} = nothing

    function TeamsLimits(active, )
        OpenAPI.validate_property(TeamsLimits, Symbol("active"), active)
        return new(active, )
    end
end # type TeamsLimits

const _property_types_TeamsLimits = Dict{Symbol,String}(Symbol("active")=>"Int64", )
OpenAPI.property_type(::Type{ TeamsLimits }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TeamsLimits[name]))}

function check_required(o::TeamsLimits)
    true
end

function OpenAPI.validate_property(::Type{ TeamsLimits }, name::Symbol, val)
end
