# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""UpdateUserCustomStatus_request

    UpdateUserCustomStatusRequest(;
        emoji=nothing,
        text=nothing,
        duration=nothing,
        expires_at=nothing,
    )

    - emoji::String : Any emoji
    - text::String : Any custom status text
    - duration::String : Duration of custom status, can be &#x60;thirty_minutes&#x60;, &#x60;one_hour&#x60;, &#x60;four_hours&#x60;, &#x60;today&#x60;, &#x60;this_week&#x60; or &#x60;date_and_time&#x60;
    - expires_at::String : The time at which custom status should be expired. It should be in ISO format.
"""
Base.@kwdef mutable struct UpdateUserCustomStatusRequest <: OpenAPI.APIModel
    emoji::Union{Nothing, String} = nothing
    text::Union{Nothing, String} = nothing
    duration::Union{Nothing, String} = nothing
    expires_at::Union{Nothing, String} = nothing

    function UpdateUserCustomStatusRequest(emoji, text, duration, expires_at, )
        OpenAPI.validate_property(UpdateUserCustomStatusRequest, Symbol("emoji"), emoji)
        OpenAPI.validate_property(UpdateUserCustomStatusRequest, Symbol("text"), text)
        OpenAPI.validate_property(UpdateUserCustomStatusRequest, Symbol("duration"), duration)
        OpenAPI.validate_property(UpdateUserCustomStatusRequest, Symbol("expires_at"), expires_at)
        return new(emoji, text, duration, expires_at, )
    end
end # type UpdateUserCustomStatusRequest

const _property_types_UpdateUserCustomStatusRequest = Dict{Symbol,String}(Symbol("emoji")=>"String", Symbol("text")=>"String", Symbol("duration")=>"String", Symbol("expires_at")=>"String", )
OpenAPI.property_type(::Type{ UpdateUserCustomStatusRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_UpdateUserCustomStatusRequest[name]))}

function check_required(o::UpdateUserCustomStatusRequest)
    o.emoji === nothing && (return false)
    o.text === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ UpdateUserCustomStatusRequest }, name::Symbol, val)
end
