# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""OrderedSidebarCategories
List of user&#39;s categories with their channels

    OrderedSidebarCategories(;
        order=nothing,
        categories=nothing,
    )

    - order::Vector{String}
    - categories::Vector{SidebarCategoryWithChannels}
"""
Base.@kwdef mutable struct OrderedSidebarCategories <: OpenAPI.APIModel
    order::Union{Nothing, Vector{String}} = nothing
    categories::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{SidebarCategoryWithChannels} }

    function OrderedSidebarCategories(order, categories, )
        OpenAPI.validate_property(OrderedSidebarCategories, Symbol("order"), order)
        OpenAPI.validate_property(OrderedSidebarCategories, Symbol("categories"), categories)
        return new(order, categories, )
    end
end # type OrderedSidebarCategories

const _property_types_OrderedSidebarCategories = Dict{Symbol,String}(Symbol("order")=>"Vector{String}", Symbol("categories")=>"Vector{SidebarCategoryWithChannels}", )
OpenAPI.property_type(::Type{ OrderedSidebarCategories }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_OrderedSidebarCategories[name]))}

function check_required(o::OrderedSidebarCategories)
    true
end

function OpenAPI.validate_property(::Type{ OrderedSidebarCategories }, name::Symbol, val)
end
