# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""WebhookOnCreationPayload_allOf

    WebhookOnCreationPayloadAllOf(;
        channel_url=nothing,
        details_url=nothing,
    )

    - channel_url::String : Absolute URL to the playbook run&#39;s channel.
    - details_url::String : Absolute URL to the playbook run&#39;s details.
"""
Base.@kwdef mutable struct WebhookOnCreationPayloadAllOf <: OpenAPI.APIModel
    channel_url::Union{Nothing, String} = nothing
    details_url::Union{Nothing, String} = nothing

    function WebhookOnCreationPayloadAllOf(channel_url, details_url, )
        OpenAPI.validate_property(WebhookOnCreationPayloadAllOf, Symbol("channel_url"), channel_url)
        OpenAPI.validate_property(WebhookOnCreationPayloadAllOf, Symbol("details_url"), details_url)
        return new(channel_url, details_url, )
    end
end # type WebhookOnCreationPayloadAllOf

const _property_types_WebhookOnCreationPayloadAllOf = Dict{Symbol,String}(Symbol("channel_url")=>"String", Symbol("details_url")=>"String", )
OpenAPI.property_type(::Type{ WebhookOnCreationPayloadAllOf }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_WebhookOnCreationPayloadAllOf[name]))}

function check_required(o::WebhookOnCreationPayloadAllOf)
    true
end

function OpenAPI.validate_property(::Type{ WebhookOnCreationPayloadAllOf }, name::Symbol, val)
end
