# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""OpenGraph_videos_inner
Video object used in OpenGraph metadata of a webpage

    OpenGraphVideosInner(;
        url=nothing,
        secure_url=nothing,
        type=nothing,
        width=nothing,
        height=nothing,
    )

    - url::String
    - secure_url::String
    - type::String
    - width::Int64
    - height::Int64
"""
Base.@kwdef mutable struct OpenGraphVideosInner <: OpenAPI.APIModel
    url::Union{Nothing, String} = nothing
    secure_url::Union{Nothing, String} = nothing
    type::Union{Nothing, String} = nothing
    width::Union{Nothing, Int64} = nothing
    height::Union{Nothing, Int64} = nothing

    function OpenGraphVideosInner(url, secure_url, type, width, height, )
        OpenAPI.validate_property(OpenGraphVideosInner, Symbol("url"), url)
        OpenAPI.validate_property(OpenGraphVideosInner, Symbol("secure_url"), secure_url)
        OpenAPI.validate_property(OpenGraphVideosInner, Symbol("type"), type)
        OpenAPI.validate_property(OpenGraphVideosInner, Symbol("width"), width)
        OpenAPI.validate_property(OpenGraphVideosInner, Symbol("height"), height)
        return new(url, secure_url, type, width, height, )
    end
end # type OpenGraphVideosInner

const _property_types_OpenGraphVideosInner = Dict{Symbol,String}(Symbol("url")=>"String", Symbol("secure_url")=>"String", Symbol("type")=>"String", Symbol("width")=>"Int64", Symbol("height")=>"Int64", )
OpenAPI.property_type(::Type{ OpenGraphVideosInner }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_OpenGraphVideosInner[name]))}

function check_required(o::OpenGraphVideosInner)
    true
end

function OpenAPI.validate_property(::Type{ OpenGraphVideosInner }, name::Symbol, val)
end
