# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Config_ClusterSettings

    ConfigClusterSettings(;
        Enable=nothing,
        InterNodeListenAddress=nothing,
        InterNodeUrls=nothing,
    )

    - Enable::Bool
    - InterNodeListenAddress::String
    - InterNodeUrls::Vector{String}
"""
Base.@kwdef mutable struct ConfigClusterSettings <: OpenAPI.APIModel
    Enable::Union{Nothing, Bool} = nothing
    InterNodeListenAddress::Union{Nothing, String} = nothing
    InterNodeUrls::Union{Nothing, Vector{String}} = nothing

    function ConfigClusterSettings(Enable, InterNodeListenAddress, InterNodeUrls, )
        OpenAPI.validate_property(ConfigClusterSettings, Symbol("Enable"), Enable)
        OpenAPI.validate_property(ConfigClusterSettings, Symbol("InterNodeListenAddress"), InterNodeListenAddress)
        OpenAPI.validate_property(ConfigClusterSettings, Symbol("InterNodeUrls"), InterNodeUrls)
        return new(Enable, InterNodeListenAddress, InterNodeUrls, )
    end
end # type ConfigClusterSettings

const _property_types_ConfigClusterSettings = Dict{Symbol,String}(Symbol("Enable")=>"Bool", Symbol("InterNodeListenAddress")=>"String", Symbol("InterNodeUrls")=>"Vector{String}", )
OpenAPI.property_type(::Type{ ConfigClusterSettings }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ConfigClusterSettings[name]))}

function check_required(o::ConfigClusterSettings)
    true
end

function OpenAPI.validate_property(::Type{ ConfigClusterSettings }, name::Symbol, val)
end
