# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ResetSamlAuthDataToEmail_200_response

    ResetSamlAuthDataToEmail200Response(;
        num_affected=nothing,
    )

    - num_affected::Int64 : The number of users whose AuthData field was reset.
"""
Base.@kwdef mutable struct ResetSamlAuthDataToEmail200Response <: OpenAPI.APIModel
    num_affected::Union{Nothing, Int64} = nothing

    function ResetSamlAuthDataToEmail200Response(num_affected, )
        OpenAPI.validate_property(ResetSamlAuthDataToEmail200Response, Symbol("num_affected"), num_affected)
        return new(num_affected, )
    end
end # type ResetSamlAuthDataToEmail200Response

const _property_types_ResetSamlAuthDataToEmail200Response = Dict{Symbol,String}(Symbol("num_affected")=>"Int64", )
OpenAPI.property_type(::Type{ ResetSamlAuthDataToEmail200Response }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ResetSamlAuthDataToEmail200Response[name]))}

function check_required(o::ResetSamlAuthDataToEmail200Response)
    true
end

function OpenAPI.validate_property(::Type{ ResetSamlAuthDataToEmail200Response }, name::Symbol, val)
end
