# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""RetentionPolicyForTeamList

    RetentionPolicyForTeamList(;
        policies=nothing,
        total_count=nothing,
    )

    - policies::Vector{DataRetentionPolicyForTeam} : The list of team policies.
    - total_count::Int64 : The total number of team policies.
"""
Base.@kwdef mutable struct RetentionPolicyForTeamList <: OpenAPI.APIModel
    policies::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{DataRetentionPolicyForTeam} }
    total_count::Union{Nothing, Int64} = nothing

    function RetentionPolicyForTeamList(policies, total_count, )
        OpenAPI.validate_property(RetentionPolicyForTeamList, Symbol("policies"), policies)
        OpenAPI.validate_property(RetentionPolicyForTeamList, Symbol("total_count"), total_count)
        return new(policies, total_count, )
    end
end # type RetentionPolicyForTeamList

const _property_types_RetentionPolicyForTeamList = Dict{Symbol,String}(Symbol("policies")=>"Vector{DataRetentionPolicyForTeam}", Symbol("total_count")=>"Int64", )
OpenAPI.property_type(::Type{ RetentionPolicyForTeamList }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_RetentionPolicyForTeamList[name]))}

function check_required(o::RetentionPolicyForTeamList)
    true
end

function OpenAPI.validate_property(::Type{ RetentionPolicyForTeamList }, name::Symbol, val)
end
