# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""itemRename_request

    ItemRenameRequest(;
        title=nothing,
        command=nothing,
    )

    - title::String : The new title of the item.
    - command::String : The new slash command of the item.
"""
Base.@kwdef mutable struct ItemRenameRequest <: OpenAPI.APIModel
    title::Union{Nothing, String} = nothing
    command::Union{Nothing, String} = nothing

    function ItemRenameRequest(title, command, )
        OpenAPI.validate_property(ItemRenameRequest, Symbol("title"), title)
        OpenAPI.validate_property(ItemRenameRequest, Symbol("command"), command)
        return new(title, command, )
    end
end # type ItemRenameRequest

const _property_types_ItemRenameRequest = Dict{Symbol,String}(Symbol("title")=>"String", Symbol("command")=>"String", )
OpenAPI.property_type(::Type{ ItemRenameRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ItemRenameRequest[name]))}

function check_required(o::ItemRenameRequest)
    o.title === nothing && (return false)
    o.command === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ ItemRenameRequest }, name::Symbol, val)
end
